Repository ayshiff/madu_app, pull requests merged in 2020-07, with the labels that each got.

#6 [STYLING] v2
  .detoxrc.json
  app.json
  assets/welcome.png
  e2e/config.json
  e2e/firstTest.spec.js
  e2e/init.js
  e2e/login_a_user.js
  e2e/register_a_new_user.js
  jest.config.js
  package.json
  src/app/components/atoms/button/button.presets.ts
  src/app/components/atoms/camera/camera.tsx
  src/app/components/atoms/icon/icons/index.ts
  src/app/components/atoms/icon/icons/logout.png
  src/app/components/atoms/input/input.tsx
  src/app/components/atoms/text/text.presets.ts
  src/app/components/organisms/header/header.props.ts
  src/app/components/organisms/header/header.tsx
  src/app/components/templates/welcome/login/index.tsx
  src/app/components/templates/welcome/register/step-five.tsx
  src/app/components/templates/welcome/register/step-four.tsx
  src/app/components/templates/welcome/register/step-one.tsx
  src/app/components/templates/welcome/register/step-six.tsx
  src/app/components/templates/welcome/register/step-three.tsx
  src/app/components/templates/welcome/register/step-two.tsx
  src/app/screens/content-screen/content-screen.tsx
  src/app/screens/home-screen/home-screen.tsx
  src/app/screens/map-screen/map-screen.tsx
  src/app/screens/profile-screen/profile-screen.tsx
  src/app/screens/welcome-screen/welcome-screen.tsx
  src/app/theme/color.ts
  src/app/theme/palette.ts
  src/assets/avatar.png
  yarn.lock
Labels: enhancement, styling

#10 Feature/challenge component
  .detoxrc.json
  .eslintrc.js
  .expo-shared/assets.json
  app.json
  assets/crown.png
  assets/down.png
  assets/electricity.png
  assets/meal-200-200.png
  assets/meal-375-214.png
  assets/meal.png
  assets/profile-pic.png
  assets/up.png
  package.json
  src/app/components/templates/challenge/challenge-main-step.tsx
  src/app/components/templates/challenge/challenge-picture-step.tsx
  src/app/components/templates/challenge/challenge-success-step.tsx
  src/app/navigation/challenge-navigator.tsx
  src/app/navigation/home-navigator.tsx
  src/app/screens/detail-screen/detail-screen.tsx
  src/app/screens/home-screen/home-screen.tsx
  src/app/screens/index.ts
  src/app/screens/leaderboard-screen/leaderboard-screen.tsx
  tsconfig.json
Labels: enhancement

#12 feat(docs): update README
  README.md
Labels: documentation

#13 fix(core): navigation + small issues
  package.json
  src/App.tsx
  src/actions/challenge.actions.ts
  src/actions/image.actions.ts
  src/actions/poi.actions.ts
  src/actions/profile.actions.ts
  src/actions/register.actions.ts
  src/components/atoms/button/button.tsx
  src/components/atoms/icon/icons/index.ts
  src/components/atoms/icon/icons/like2.png
  src/components/atoms/old-button/old-button.presets.tsx
  src/components/atoms/old-button/old-button.props.ts
  src/components/atoms/old-button/old-button.tsx
  src/components/atoms/old-text/old-text.presets.ts
  src/components/atoms/old-text/old-text.props.ts
  src/components/atoms/old-text/old-text.tsx
  src/components/atoms/points/points.tsx
  src/components/organisms/map/map.tsx
  src/components/templates/welcome/login/index.tsx
  src/components/templates/welcome/register/step-five.tsx
  src/components/templates/welcome/register/step-four.tsx
  src/components/templates/welcome/register/step-one.tsx
  src/components/templates/welcome/register/step-six.tsx
  src/components/templates/welcome/register/step-three.tsx
  src/components/templates/welcome/register/step-two.tsx
  src/const.ts
  src/epics/challenge.epic.ts
  src/epics/image.epic.ts
  src/epics/login.epic.ts
  src/epics/poi.epic.ts
  src/epics/profile.epic.ts
  src/epics/register.epic.ts
  src/epics/root.epic.ts
  src/navigation/challenge-navigator.tsx
  src/navigation/home/home-navigator-token.tsx
  src/navigation/home/home-navigator.tsx
  src/navigation/index.ts
  src/navigation/types.ts
  src/navigation/welcome-navigator.tsx
  src/screens/home-screen/home-screen.tsx
  src/screens/index.ts
  src/screens/map-screen/map-screen.tsx
  src/screens/poi-screen/poi-screen.tsx
  src/screens/poi-success-screen/poi-success-screen.tsx
  src/store/challenge.reducer.ts
  src/store/image.reducer.ts
  src/store/poi.reducer.ts
  src/store/profile.reducer.ts
  src/store/register.reducer.ts
  src/store/root.reducer.ts
  src/store/utils.ts
Labels: bug

#18 Feaure: back integration
  src/actions/challenge.actions.ts
  src/actions/leaderboard.actions.ts
  src/actions/profile.actions.ts
  src/assets/profile-pic.png
  src/components/atoms/icon/icons/challenge_done.png
  src/components/atoms/icon/icons/index.ts
  src/components/organisms/map/map.tsx
  src/components/templates/challenge/challenge-main-step.tsx
  src/components/templates/challenge/challenge-success-step.tsx
  src/components/templates/leaderboard/collective-leaderboard.tsx
  src/components/templates/leaderboard/individual-leaderboard.tsx
  src/components/templates/profile/challenge-done.tsx
  src/components/templates/profile/profile-settings.tsx
  src/components/templates/profile/visited-places.tsx
  src/components/templates/welcome/register/step-five.tsx
  src/epics/challenge.epic.ts
  src/epics/leaderboard.epic.ts
  src/epics/profile.epic.ts
  src/epics/root.epic.ts
  src/screens/home-screen/home-screen.tsx
  src/screens/leaderboard-screen/leaderboard-screen.tsx
  src/screens/map-screen/map-screen.tsx
  src/screens/poi-screen/poi-screen.tsx
  src/screens/profile-screen/profile-screen.tsx
  src/store/challenge.reducer.ts
  src/store/leaderboard.reducer.ts
  src/store/profile.reducer.ts
  src/store/root.reducer.ts
Labels: enhancement
